spring:
  application:
    name: HyeroMap_BE

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://${DB_HOST:${MYSQL_HOST}}:${DB_PORT:${MYSQL_PORT}}/${DB_NAME:${MYSQL_DATABASE}}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: ${DB_USERNAME:${MYSQL_USER}}
    password: ${DB_PASSWORD:${MYSQL_PASSWORD}}
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: update  # none
      properties:
        hibernate:
          show_sql: true  # false
          format_sql: true # show_sql 설정